FileUploadTest.KPMG/WebKPMG/Controllers/TaxDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KPMGTest.Model;
using WebKPMG.Models;
using KPMGTest.Interface;
using KPMGTest.Data;
using System.Data.Entity;
namespace WebKPMG.Controllers
{
    public class TaxDetailsController : Controller
    {
        public readonly ITaxInfoRepository _Taxinfo;


        public TaxDetailsController(ITaxInfoRepository Taxinfo)
        {
            this._Taxinfo = Taxinfo;
        }

        // GET: TaxDetails
         [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Gettaxinfo()
         {
            var list = _Taxinfo.TaxinfoQuery.ToList();
            var jsonData = new
            {
                data = list
            };
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult GetRowbyId(int Id)
        {
            var success = true;
            var row = _Taxinfo.TaxinfoQuery.Where(x => x.TaxId == Id).FirstOrDefault();
            return Json(new { Success = success, row = row }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Save(TaxInfoViewModel model)
        {
            var success = true;
            var details = new Tax_Information
            {
                Account = model.Account,
                Description = model.Description,
                Currency = model.Currency,
                Amount = Convert.ToDecimal(model.Amount),

            };
            if (model.TaxId != 0)
                details.TaxId = model.TaxId;
            _Taxinfo.Save(details);
            return Json(new { Success = success }, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public JsonResult Delete(int Id)
        {
            var success = true;
            _Taxinfo.Delete(Id);
            return Json(new { Success = success }, JsonRequestBehavior.AllowGet);

        }
      
       
    }
}

FileUploadTest.KPMG/WebKPMG/Controllers/TaxInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Data;
using System.Text;
using KPMGTest.Model;
using WebKPMG.Models;
using KPMGTest.Interface;
using KPMGTest.Data;
using System.Collections;
using System.Globalization;
using System.Text.RegularExpressions;
using System.Data.OleDb;




namespace WebKPMG.Controllers
{
    public class TaxInfoController : Controller
    {
        public readonly ITaxInfoRepository _Taxinfo;
        DataTable dt = new DataTable();
      


        public TaxInfoController(ITaxInfoRepository Taxinfo)
        {
            this._Taxinfo = Taxinfo;
        }

    
        // GET: TaxInfo
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file_Uploader)
        {
           
            List<ErrorlistViewModel> error = new List<ErrorlistViewModel>();
            List<TaxInfoViewModel> taxinfo = new List<TaxInfoViewModel>();
            
            if (file_Uploader != null)
            {

                string fileName = string.Empty;
                string destinationPath = string.Empty;
             
                string connString = "";
             
                fileName = Path.GetFileName(file_Uploader.FileName);

                destinationPath = Path.Combine(Server.MapPath("~/App_Data/"), fileName);
                file_Uploader.SaveAs(destinationPath);

                //Start file processing ere

                //IF file tye CSV
                if (file_Uploader.FileName.EndsWith(".csv"))
                {
 
                    using (StreamReader sr = new StreamReader(destinationPath))
                    {
                        
                        int rownum = 1;
                        string errortype="";
                        

                        while (!sr.EndOfStream)
                        {
                           
                            string[] rows = sr.ReadLine().Split(',');
                           
                            ErrorlistViewModel er = new ErrorlistViewModel();
                            TaxInfoViewModel info = new TaxInfoViewModel();

                           //DO Validate

                            errortype = _Taxinfo.Dovalidate(rows[0].ToString(), rows[1].ToString(), rows[2].ToString(), rows[3].ToString());
                            
                              
                                if (errortype != "")
                               {
                                   er.row = rownum;
                                   er.Error = errortype;
                                   error.Add(er);

                                   
                               }
                               
                               if(error.Count==0)
                               {
                                  

                                   info.Account = rows[0];
                                   info.Description = rows[1];
                                   info.Currency = rows[2];
                                   info.Amount = Convert.ToDecimal(rows[3]);

                                   taxinfo.Add(info);
                                   
                               }

                               errortype = "";
                               rownum = rownum + 1;
                        
                        }


                        if (error.Count>0)
                        {
                            ViewBag.Message = "Please Correct following errors!! and Re Upload.";
                            return View(error);
                        }
                        else
                        {

                            for (var i = 0; i < taxinfo.Count; i++)
                            {
                                 var details = new Tax_Information

                                 {
                                     Account = taxinfo[i].Account,
                                     Description = taxinfo[i].Description,
                                     Currency = taxinfo[i].Currency,
                                     Amount = Convert.ToDecimal(taxinfo[i].Amount),

                                 };
                  
                                    _Taxinfo.Save(details);

                            }

                                ViewBag.Message = "Data Saved Successfully.";
                            
                        }
                 

                        
                    }
                  
                }

                //IF file tye Xls
                else if (file_Uploader.FileName.EndsWith(".xls"))
                {
                    string errortype = "";
                    ErrorlistViewModel er = new ErrorlistViewModel();
                    TaxInfoViewModel info = new TaxInfoViewModel();
                    connString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" + destinationPath + ";Extended Properties=\"Excel 8.0;HDR=Yes;IMEX=2\"";

                    dt = _Taxinfo.ConvertXSLXtoDataTable(destinationPath, connString);

                    for (int i = 0; i < dt.Rows.Count; i++)
                    {
                        //DO Validate

                        errortype = _Taxinfo.Dovalidate(dt.Rows[i][0].ToString(), dt.Rows[i][1].ToString(), dt.Rows[i][2].ToString(), dt.Rows[i][3].ToString());

                        if (errortype != "")
                        {
                            er.row = i;
                            er.Error = errortype;
                            error.Add(er);


                        }

                        if (error.Count == 0)
                        {


                            info.Account = dt.Rows[i][0].ToString();
                            info.Description = dt.Rows[i][1].ToString();
                            info.Currency = dt.Rows[i][2].ToString();
                            info.Amount = Convert.ToDecimal(dt.Rows[i][3].ToString());

                            taxinfo.Add(info);

                        }
                            
                    }


                    if (error.Count > 0)
                    {
                        ViewBag.Message = "Please Correct following errors!! and Re Upload.";
                        return View(error);
                    }
                    else
                    {

                        for (var i = 0; i < taxinfo.Count; i++)
                        {
                            var details = new Tax_Information
                            {
                                Account = taxinfo[i].Account,
                                Description = taxinfo[i].Description,
                                Currency = taxinfo[i].Currency,
                                Amount = Convert.ToDecimal(taxinfo[i].Amount),

                            };
                            _Taxinfo.Save(details);

                        }

                        ViewBag.Message = "Data Saved Successfully.";

                    }
                 

                        
               
                 
                }
                //IF file tye Xlsx
                else if (file_Uploader.FileName.EndsWith(".xlsx"))
                {
                    string errortype = "";
                    ErrorlistViewModel er = new ErrorlistViewModel();
                    TaxInfoViewModel info = new TaxInfoViewModel();
                    connString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + destinationPath + ";Extended Properties=\"Excel 12.0;HDR=Yes;IMEX=2\"";

                    dt = _Taxinfo.ConvertXSLXtoDataTable(destinationPath, connString);

                    for (int i = 0; i < dt.Rows.Count; i++)
                    {
                        //DO Validate

                        errortype = _Taxinfo.Dovalidate(dt.Rows[i][0].ToString(), dt.Rows[i][1].ToString(), dt.Rows[i][2].ToString(), dt.Rows[i][3].ToString());

                        if (errortype != "")
                        {
                            er.row = i+1;
                            er.Error = errortype;
                            error.Add(er);


                        }

                        if (error.Count == 0)
                        {


                            info.Account = dt.Rows[i][0].ToString();
                            info.Description = dt.Rows[i][1].ToString();
                            info.Currency = dt.Rows[i][2].ToString();
                            info.Amount = Convert.ToDecimal(dt.Rows[i][3].ToString());

                            taxinfo.Add(info);

                        }

                    }


                    if (error.Count > 0)
                    {
                        ViewBag.Message = "Please Correct following errors!! and Re Upload.";
                        return View(error);
                    }
                    else
                    {

                        for (var i = 0; i < taxinfo.Count; i++)
                        {
                            var details = new Tax_Information
                            {
                                Account = taxinfo[i].Account,
                                Description = taxinfo[i].Description,
                                Currency = taxinfo[i].Currency,
                                Amount = Convert.ToDecimal(taxinfo[i].Amount),

                            };
                            _Taxinfo.Save(details);

                        }

                        ViewBag.Message = "Data Saved Successfully.";

                    }
                 

                }  
                else
                {
                    ViewBag.Message = "Please Upload Files in .xls, .xlsx or .csv format";

                }
 

                return View();

            }

FileUploadTest.KPMG/WebKPMG/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Freelancer - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="~/UIScripts/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="~/UIScripts/css/freelancer.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="~/UIScripts/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>




<body id="page-top" class="index">
    <!-- Wrapper-->
    <!-- PageClass give you ability to specify custom style for specific view based on action -->
    @Html.Partial("_TopNavbar")



   
    
            @RenderBody()
         


        @Html.Partial("_footer")

        <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
        <div class="scroll-top page-scroll hidden-sm hidden-xs hidden-lg hidden-md">
            <a class="btn btn-primary" href="#page-top">
                <i class="fa fa-chevron-up"></i>
            </a>
        </div>

    <div class="ui small modal" id="CustomAlert" style="height:200px">
        <div class="header">
            Information
        </div>
        <div class="content">
            <div class="description">
                Please select the row
            </div>
        </div>
        <div class="actions">
        </div>
    </div>

        <!-- jQuery -->
        <script src="~/UIScripts/vendor/jquery/jquery.min.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="~/UIScripts/vendor/bootstrap/js/bootstrap.min.js"></script>

        <!-- Plugin JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

        <!-- Contact Form JavaScript -->
        <script src="~/UIScripts/js/jqBootstrapValidation.js"></script>
        <script src="~/UIScripts/js/contact_me.js"></script>

        <!-- Theme JavaScript -->
        <script src="~/UIScripts/js/freelancer.min.js"></script>
    @Scripts.Render("~/app/CustomAlert")

        @RenderSection("scripts", required: false)




</body>
</html>

FileUploadTest.KPMG/WebKPMG/Views/Shared/_TopNavbar.cshtml
 <!-- Navigation -->
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="#page-top">KPMG</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li class="page-scroll">
                    <a href="@Url.Action("Index", "Home") ">Home</a>
                </li>
                <li class="page-scroll">
                    <a href="@Url.Action("Index", "TaxInfo")">Upload</a>
                </li>
                <li class="page-scroll">
                    <a href="@Url.Action("Index", "TaxDetails")">Tax Information</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

FileUploadTest.KPMG/WebKPMG/Views/Shared/_footer.cshtml
<!-- Footer -->
<footer class="text-center">
    <div class="footer-above">
        <div class="container">
            <div class="row">
                <div class="footer-col col-md-4">
                    <h3>Location</h3>
                    <p>
                        3481 Melrose Place
                        <br>Beverly Hills, CA 90210
                    </p>
                </div>
                <div class="footer-col col-md-4">
                    <h3>Around the Web</h3>
                    <ul class="list-inline">
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-dribbble"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="footer-col col-md-4">
                    <h3>About Freelancer</h3>
                    <p>Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-below">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    Copyright &copy; Your Website 2016
                </div>
            </div>
        </div>
    </div>
</footer>